touch_on_select 1
# When an entry is selected via clipmenu(1) it will also be 
# moved up to the newest slot.  Default: 0.

deduplicate 1
# If set to 1, clipmenud keeps only the newest 
# copy of duplicate clips instead of storing every 
# duplicate entry. Default: 0.

max_clips 1000
# Specifies  the  maximum  number  of clipboard 
# entries to retain in the clip store.  Default: 1000.

max_clips_batch 100
# Provides a buffer above max_clips;
# when the number  of  entries  exceeds (max_clips  + max_clips_batch), 
# the clip store is trimmed back to max_clips entries. Default: 100.

