#!/bin/bash

PINENTRY="/usr/local/bin/pinentry-dmenu"

# Получение пароля
if [ -x "$PINENTRY" ]; then
    PASSWORD=$(
        printf "SETTITLE GPG\nSETPROMPT Введіть пароль:\nGETPIN\n" | "$PINENTRY" \
        | awk -F' ' '/^D / {print substr($0,3)}'
    )

    if [ -z "$PASSWORD" ]; then
        echo "Пароль не введено."
        exit 1
    fi
else
    echo -n "Введіть пароль: "
    read -s PASSWORD
    echo
fi

# Расшифровка файлов
find . -type f -name "*.gpg" | while read -r file
do
    echo "Розшифрування файла: $file"
    tmpfile=$(mktemp /dev/shm/tmp.XXXXXX)

    if echo "$PASSWORD" | gpg --batch --yes --passphrase-fd 0 --decrypt "$file" > "$tmpfile"; then
        mv "$tmpfile" "${file%.gpg}"
        echo "Файл розшифрований: $file"
    else
        echo "Помилка розшифрування файла: $file"
        rm -f "$tmpfile"
    fi
done

