#!/bin/bash

python_script="$HOME/awards/drs/drs_wx.bin"
data_file="/mnt/chromeos/removable/SD Card/now/STATYSTYKA/NN/db.db"

xsetroot -name "    "

if [ ! -f "$data_file" ]; then
    echo "Файл $data_file не знайдено."
    dunstify -u critical "Файл $data_file не знайдено."
    exit 1
fi

"$python_script" -c "$data_file" 2>/dev/null &
APP_PID=$!
    
PW_SWITCHED=0
MAIN_SWITCHED=0

while kill -0 $APP_PID 2>/dev/null; do
    PW_WIN=$(xdotool search --name "Пароль" 2>/dev/null | tail -n 1)

    if [ -n "$PW_WIN" ]; then
        if [ "$PW_SWITCHED" -eq 0 ]; then
            xkb-switch -s us
            xdotool windowactivate "$PW_WIN"
            pkill -RTMIN+1 dwmblocks
            PW_SWITCHED=1
        fi
    else
        if [ "$PW_SWITCHED" -eq 1 ]; then
            
            MAIN_WIN=$(xdotool search --class "Drs_wx" 2>/dev/null | tail -n 1)
            
            if [ -n "$MAIN_WIN" ] && [ "$MAIN_SWITCHED" -eq 0 ]; then
                xkb-switch -s ua
                xdotool windowactivate "$MAIN_WIN"
                pkill -RTMIN+1 dwmblocks
                MAIN_SWITCHED=1
                
                break 
            fi
        fi
    fi

    sleep 0.2
done

xsetroot -name ""
